//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeWebMail.Infrastructure.Resources.Sql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeeWebMail.Infrastructure.Resources.Sql.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT mbx.mbx_id 
        ///	, mbx.mbx_domain_name 	
        ///	, mbx.mbx_imap_address
        ///	, mbx.mbx_imap_port
        ///	, mbx.mbx_smtp_address
        ///	, mbx.mbx_smtp_port
        ///	, mbx.mbx_smtp_ssl
        ///	, mbx.mbx_imap_ssl
        ///FROM mailboxes mbx
        ///WHERE mbx.mbx_domain_name = @DomainName
        ///.
        /// </summary>
        public static string GetMailbox {
            get {
                return ResourceManager.GetString("GetMailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT usr.usr_id
        ///	, usr.usr_email
        ///	, usr.usr_admin
        ///	, mbx.mbx_id
        ///	, mbx.mbx_imap_address
        ///	, mbx.mbx_imap_port
        ///	, mbx.mbx_smtp_address
        ///	, mbx.mbx_smtp_port
        ///	, mbx.mbx_smtp_ssl
        ///	, mbx.mbx_imap_ssl
        ///	, mbx.mbx_domain_name
        ///FROM users usr JOIN mailboxes mbx ON usr.mbx_id = mbx.mbx_id
        ///WHERE usr.usr_email = @UserEmail
        ///.
        /// </summary>
        public static string GetUsers {
            get {
                return ResourceManager.GetString("GetUsers", resourceCulture);
            }
        }
    }
}
